[feature] #34 支持使用反射设置参数
CuteReimu/bilibili pull request #36
Opened 2024-03-28 14:31 UTC by RunsTp

支持使用反射设置 `resty.Request` 的参数
目前使用的tag情况
- `request` 使用此tag name进行解析
- `query` 代表参数附加到 query中
- `json`和 `form-data` 代表参数附加到 body中 会分别附加对应的content-type
- `omitempty` 标记为omitempty的参数在零值时不会被附加到参数中
- `field` 默认使用 struct.FieldName 转蛇形作为参数名, 如果指定了field 则使用field的声明
- `default` 默认值,在参数为零值且未标记omitempty的时候使用

目前的考虑
- default会默认使用string类型 在部分json的场合可能不合适,可以为int 和float类型参数做特别转换
- 单独使用field可能会导致设置时非常繁琐，在考虑是否使用query=xxx or json=xxx 这种方式

2024-03-29 03:15 UTC, CuteReimu commented
我这边其实是不建议我们写default的，因为实在是太加大我们的开发工作量了。因为B站自己有default，我们不填这个字段他就会取default，这个default是B站的default而不应该是我们的default。所以我建议是支持omitempty就好了。

2024-03-29 03:20 UTC, CuteReimu commented
> 我这边其实是不建议我们写default的，因为实在是太加大我们的开发工作量了。因为B站自己有default，我们不填这个字段他就会取default，这个default是B站的default而不应该是我们的default。所以我建议是支持omitempty就好了。

不过我觉得问题也不大，多支持一点功能也好，我们实际开发过程中也不一定非要用

2024-03-29 03:58 UTC, CuteReimu commented on util.go
> +		}
这里有点问题。
外面有一个大循环：
```go
for i := 0; i < inType.NumField(); i++ {
	// xxxxxx
	if tValue == "" || tValue == "-" {
		continue
	}
```
所以这里会`SetHeader`好几遍，结果以最后一个非空的为准了。

2024-03-29 03:58 UTC, CuteReimu commented on util.go
> +			realVal = fieldValue.Elem().Interface()
这一段就不处理tag了吗？

2024-03-29 03:58 UTC, CuteReimu commented on util.go
> +		}
上面已经有了：
```go
if in == nil {
    return nil
}

2024-03-29 04:06 UTC, RunsTp commented on util.go
> +		}
好的，我来处理这个问题

2024-03-29 04:08 UTC, RunsTp commented on util.go
> +			realVal = fieldValue.Elem().Interface()
我认为一个field的类型是 Ptr 并且这个Ptr是nil 其实就不必处理了。
因为这里就算处理也仅仅是设置default。所以我把 Ptr == nil 和 非Ptr 设置 omitempty的概念统一了

2024-03-29 04:10 UTC, RunsTp commented on util.go
> +		}
这里还是要设置这个判断的，因为存在 nil != nil 的经典问题

2024-03-29 04:10 UTC, CuteReimu requested changes

2024-03-29 04:10 UTC, CuteReimu commented on util.go
> +					realVal = reflect.Zero(fieldType.Type).Interface()
这里直接把fieldValue的值拿来用就行了，反正前面有
 ```go
if fieldValue.IsZero() {
```

2024-03-29 04:14 UTC, CuteReimu commented on util.go
> +		}
加个测试用例吧
```go
err = withParams(r, (*int)(nil))
```
我刚才覆盖率测试没跑到

2024-03-29 04:20 UTC, CuteReimu commented on util.go
> +			realVal = fieldValue.Elem().Interface()
嗯，在这种特殊的情况下确实问题不大，因为请求参数不会有null的情况，例如这种
```go
type A struct {
   Field *int // 然后这里没有omitempty
}

withParam(r, A{Field: nil})
```

2024-03-29 23:05 UTC, merged

2024-03-29 23:06 UTC, RunsTp commented
我合并了此分支，如果你有进一步的修改，直接修改即可

2024-03-31 02:53 UTC, CuteReimu commented
我印象中，本来就有一个form-data的contentType。另外queryParam好像才应该是那个www-urlencode的那个

2024-03-31 03:02 UTC, RunsTp commented
> 我印象中，本来就有一个form-data的contentType。另外queryParam好像才应该是那个www-urlencode的那个

是的没错 是两个