增加了一个用于方便处理分区信息的工具
CuteReimu/bilibili pull request #48
Opened 2024-04-26 17:28 UTC by PastGone

增加了一个用于方便处理分区的工具。
具体功能见函数及结构体描述

2024-04-26 17:42 UTC, CuteReimu commented
这个我记得不行吧，别人引用这个库好像csv文件不会被打包进去。你用`go:embed`写试试

2024-04-26 18:01 UTC, CuteReimu commented
测了，不能用。测试代码：

`go.mod`文件：

```go
module test

go 1.22

replace github.com/CuteReimu/bilibili/v2 => E:\GoProject\bilibili
```

然后执行

```bash
go get github.com/CuteReimu/bilibili/v2
```

`main.go`文件：

```go
package main

import (
	"fmt"
	"github.com/CuteReimu/bilibili/v2"
)

func main() {
	infos, err := bilibili.GetAllZoneInfos()
	if err != nil {
		panic(err)
	}
	fmt.Println(infos)
}
```

运行结果：

```console
Error opening file: open zone.csv: The system cannot find the file specified.
panic: open zone.csv: The system cannot find the file specified.

goroutine 1 [running]:
main.main()
        E:/GoProject/test/main.go:11 +0x8e
```

2024-04-26 19:05 UTC, CuteReimu requested changes
顺便处理一下golangci-lint检查的问题吧：https://github.com/CuteReimu/bilibili/pull/48/files

统一用`github.com/pkg/errors`包，`err`返回前用一下`errors.WithStack(err)`，方便调用者定位堆栈。

下面那个`fmt.Errorf`可以改成`errors.Errorf`（有参数）或者`errors.New`（无参数）

参考：

https://github.com/CuteReimu/bilibili/blob/b7561dab24b08f3b7d24fc2a9bf8f312afdd0856/util.go#L70-L76

2024-04-26 19:17 UTC, CuteReimu commented on zone_test.go
`zone_test.go`可以考虑不提上来，毕竟不能全覆盖，因此也没什么意义了。

2024-04-27 03:52 UTC, PastGone commented
另外，CSV文件好像有点问题。我先改一下，再提一个pr上来

2024-04-27 03:52 UTC, closed without merging